name: Build

on: push

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build App for Windows
              if: matrix.os == 'windows-latest'
              run: npm run build:win

            - name: Build App for MacOS
              if: matrix.os == 'macos-latest'
              run: npm run build:mac

            - name: Build App for Linux
              if: matrix.os == 'ubuntu-latest'
              run: npm run build:linux

            - name: Cleanup Artifacts for Windows
              if: matrix.os == 'windows-latest'
              run: |
                  npx rimraf "dist/!(*.exe)"

            - name: Cleanup Artifacts for MacOS
              if: matrix.os == 'macos-latest'
              run: |
                  npx rimraf "dist/!(*.dmg)"

            - name: Cleanup Artifacts for Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  npx rimraf "dist/!(*.deb)"

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3.0.0
              with:
                  name: ${{ matrix.os }}
                  path: dist
                  if-no-files-found: error
